// prod.js - production keys here!!
// module.exports = {
//     googleClientID: process.env.GOOGLE_CLIENT_ID,
//     googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
//     mongoURI: process.env.MONGO_URI,
//     cookieKey: process.env.COOKIE_KEY,
// };
// module.exports = {
//     googleClientID: '755536563346-0686nvvcljt13oi8vfaju5g302j6kr3e.apps.googleusercontent.com',
//     googleClientSecret: '-XDQf5UqVvyJfwY7QFnbooX0',
//     mongoURI: 'mongodb+srv://secureadmin:3pGJ9Ap6HgestQdJ@cluster0-dgyxm.mongodb.net/test?retryWrites=true&w=majority',
//     cookieKey: 'jdpoquioeykjhlkjhiquer987098513740hikfgeiurruh',
//     stripePublishableKey: process.env.STRIPE_PUBLISHABLE_KEY,
//     stripeSecretKey: process.env.STRIPE_SECRET_KEY,
//      sendGridKey: process.env.SEND_GRID_KEY,
//      redirectDomain: process.env.REDIRECT_DOMAIN,
// };

//PRODUCTION DETAIL DATABASE AND GOOGLE OAUTH CREDENTIALS

//emaily-prod mongo db -    Username secureadmin  password autogenerated - 3pGJ9Ap6HgestQdJ
//emaily-prod mongo db - connection link       mongodb+srv://secureadmin:3pGJ9Ap6HgestQdJ@cluster0-dgyxm.mongodb.net/test?retryWrites=true&w=majority





//production credentials for google api

//authorized redirect url = https://salty-ravine-87548.herokuapp.com and after authorized redirect to https://salty-ravine-87548.herokuapp.com/auth/google/callback

//client ID = 755536563346-0686nvvcljt13oi8vfaju5g302j6kr3e.apps.googleusercontent.com
//client secret = -XDQf5UqVvyJfwY7QFnbooX0
